import React, { useState, useEffect } from "react";
import {
  Sparkles,
  Flame,
  Award,
  Zap,
  CheckCircle,
  AlertCircle,
  Clock,
  Wand2,
  ListTodo,
  Calendar,
  Grid,
  Bot,
  Brain,
  Trash2,
  RefreshCw,
  Plus,
  Play,
  Heart,
  TrendingUp,
  User,
  Coffee,
  CheckCircle2,
  HelpCircle
} from "lucide-react";
import TaskForm from "./components/TaskForm";
import HabitTracker from "./components/HabitTracker";
import CalendarExport from "./components/CalendarExport";
import RescueCenter from "./components/RescueCenter";
import { Task, Habit, DailyPlanResponse, ProductivityReport } from "./types";

export default function App() {
  const [activeTab, setActiveTab] = useState<"dashboard" | "schedule" | "ai-insights" | "rescue">("dashboard");

  // Default Tasks to bootstrap a realistic High-Density workplace on first load
  const [tasks, setTasks] = useState<Task[]>(() => {
    try {
      const saved = localStorage.getItem("pilot_tasks");
      if (saved && saved !== "undefined") return JSON.parse(saved);
    } catch (e) {
      console.error("Local storage pilot_tasks load failure:", e);
    }

    return [
      {
        id: "task-1",
        title: "Draft Research Methodology Outline",
        description: "Need to formulate core research paradigms and compare quantitative metrics. Expected 90m deep work.",
        dueDate: "2026-06-23",
        category: "Study",
        estimateDuration: 90,
        urgency: "high",
        status: "pending",
        aiPriority: "high",
        aiExplanation: "Directly relates to tomorrow's paper deadline. Tackle when energy levels peak at 10 AM.",
        substeps: [
          { id: "sub-1", title: "Review literature section 4 parameters", completed: true },
          { id: "sub-2", title: "Outline hardware requirements overview", completed: false },
          { id: "sub-3", title: "Compile experimental results table", completed: false }
        ]
      },
      {
        id: "task-2",
        title: "Prepare Client brief for Project Delta",
        description: "Design presentation deck explaining the Cloud run scaling system updates.",
        dueDate: "2026-06-24",
        category: "Work",
        estimateDuration: 45,
        urgency: "medium",
        status: "pending",
        aiPriority: "medium",
        aiExplanation: "Important client showcase. High complexity but due in 24 hours.",
      },
      {
        id: "task-3",
        title: "Submit weekly expense accounting records",
        description: "Organize receipt slips and enter variables in spreadsheet ledger.",
        dueDate: "2026-06-25",
        category: "Financial",
        estimateDuration: 30,
        urgency: "low",
        status: "completed",
        aiPriority: "low",
        aiExplanation: "Routine bookkeeping. Completed on schedule."
      }
    ];
  });

  // Default Habits
  const [habits, setHabits] = useState<Habit[]>(() => {
    try {
      const saved = localStorage.getItem("pilot_habits");
      if (saved && saved !== "undefined") return JSON.parse(saved);
    } catch (e) {
      console.error("Local storage pilot_habits load failure:", e);
    }

    return [
      {
        id: "habit-1",
        name: "Deep Work Block (4 Hours)",
        frequency: "daily",
        streak: 3,
        history: {
          "2026-06-20": true,
          "2026-06-21": true,
          "2026-06-22": true,
          "2026-06-23": false
        },
        createdAt: "2026-06-19"
      },
      {
        id: "habit-2",
        name: "Read 3 Research Publications",
        frequency: "daily",
        streak: 5,
        history: {
          "2026-06-18": true,
          "2026-06-19": true,
          "2026-06-20": true,
          "2026-06-21": true,
          "2026-06-22": true,
          "2026-06-23": true
        },
        createdAt: "2026-06-17"
      },
      {
        id: "habit-3",
        name: "Posture Correction Exercises",
        frequency: "daily",
        streak: 0,
        history: {
          "2026-06-23": false
        },
        createdAt: "2026-06-22"
      }
    ];
  });

  // Daily study/work plan generated by Gemini
  const [dailyPlan, setDailyPlan] = useState<DailyPlanResponse | null>(() => {
    try {
      const saved = localStorage.getItem("pilot_daily_plan");
      if (saved && saved !== "undefined") return JSON.parse(saved);
    } catch (e) {
      console.error("Local storage pilot_daily_plan load failure:", e);
    }
    return null;
  });

  // Active AI Insights Report
  const [report, setReport] = useState<ProductivityReport | null>(() => {
    try {
      const saved = localStorage.getItem("pilot_report");
      if (saved && saved !== "undefined") return JSON.parse(saved);
    } catch (e) {
      console.error("Local storage pilot_report load failure:", e);
    }
    return null;
  });

  // Loading States
  const [isPrioritizing, setIsPrioritizing] = useState(false);
  const [isPlanning, setIsPlanning] = useState(false);
  const [isDecomposingId, setIsDecomposingId] = useState<string | null>(null);
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  const [uiFeedback, setUiFeedback] = useState<string>("");

  // Storage updates sync
  useEffect(() => {
    try {
      localStorage.setItem("pilot_tasks", JSON.stringify(tasks));
    } catch (e) {
      console.warn("Storage write failure:", e);
    }
  }, [tasks]);

  useEffect(() => {
    try {
      localStorage.setItem("pilot_habits", JSON.stringify(habits));
    } catch (e) {
      console.warn("Storage write failure:", e);
    }
  }, [habits]);

  useEffect(() => {
    if (dailyPlan) {
      try {
        localStorage.setItem("pilot_daily_plan", JSON.stringify(dailyPlan));
      } catch (e) {
        console.warn("Storage write failure:", e);
      }
    }
  }, [dailyPlan]);

  useEffect(() => {
    if (report) {
      try {
        localStorage.setItem("pilot_report", JSON.stringify(report));
      } catch (e) {
        console.warn("Storage write failure:", e);
      }
    }
  }, [report]);

  // Context-Aware Reminders logic
  const getContextReminders = () => {
    const pendingHighRisk = tasks.filter(t => t.status === "pending" && t.urgency === "high");
    const today = "2026-06-23";
    const dueToday = tasks.filter(t => t.status === "pending" && t.dueDate === today);

    const reminders = [];
    if (dueToday.length > 0) {
      reminders.push(`⚠️ ${dueToday.length} task(s) are strictly due today. Allocate time blocks instantly!`);
    }
    if (pendingHighRisk.length > 0) {
      reminders.push(`🔥 High-risk deadline detected: "${pendingHighRisk[0].title}" requires focus.`);
    }
    const undoneHabits = habits.filter(h => !h.history[today]);
    if (undoneHabits.length > 0) {
      reminders.push(`💡 Routine alignment: You have ${undoneHabits.length} daily habits yet to trigger today.`);
    }

    if (reminders.length === 0) {
      return ["✅ Looking bright! All systems operational. Your dashboard is prime."];
    }
    return reminders;
  };

  // Add Task handler
  const handleAddTask = (newTaskData: Omit<Task, "id" | "status">) => {
    const created: Task = {
      ...newTaskData,
      id: "raw-task-" + Date.now(),
      status: "pending",
      substeps: []
    };
    setTasks(prev => [created, ...prev]);
    showToast("Task cataloged! Running priority refinement increases focus.");
  };

  const showToast = (msg: string) => {
    setUiFeedback(msg);
    setTimeout(() => setUiFeedback(""), 4000);
  };

  // Toggle task completion
  const handleToggleTaskStatus = (taskId: string) => {
    setTasks(prev =>
      prev.map(t => {
        if (t.id === taskId) {
          const nextStatus = t.status === "completed" ? "pending" : "completed";
          return { ...t, status: nextStatus as any };
        }
        return t;
      })
    );
  };

  // Delete task
  const handleDeleteTask = (taskId: string) => {
    setTasks(prev => prev.filter(t => t.id !== taskId));
    showToast("Task removed from the terminal.");
  };

  // AI Task Prioritization trigger
  const handleRefinePriorities = async () => {
    setIsPrioritizing(true);
    showToast("Gemini AI is examining deadlines, duration constraints, and focus goals...");
    try {
      const res = await fetch("/api/gemini/prioritize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tasks }),
      });

      if (!res.ok) throw new Error("Failed response from Gemini prioritize.");

      const data = await res.json();
      const prioritizedList = data.prioritizedTasks;

      if (Array.isArray(prioritizedList)) {
        setTasks(prev =>
          prev.map(t => {
            const matches = prioritizedList.find((item: any) => item.id === t.id);
            if (matches) {
              return {
                ...t,
                aiPriority: matches.priority,
                aiExplanation: matches.reasoning
              };
            }
            return t;
          })
        );
        showToast("✨ Core task matrix prioritized via Gemini reasoning grids!");
      }
    } catch (err: any) {
      showToast("⚠️ AI prioritization failed to process: " + err.message);
    } finally {
      setIsPrioritizing(false);
    }
  };

  // AI Study/Work daily plan generation
  const handleGenerateDailyPlan = async () => {
    setIsPlanning(true);
    showToast("Synthesizing dynamic daily schedule for " + new Date().toLocaleDateString() + "...");
    try {
      const res = await fetch("/api/gemini/plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tasks: tasks.filter(t => t.status === "pending"),
          habits: habits.map(h => ({ name: h.name, frequency: h.frequency, streak: h.streak })),
          params: { currentDate: "2026-06-23", weekday: "Tuesday" }
        })
      });

      if (!res.ok) throw new Error("Vite backend timed out.");
      const data = await res.json();
      setDailyPlan(data);
      showToast("✨ AI timetabled hourly agenda updated successfully.");
    } catch (err: any) {
      showToast("⚠️ Scheduling generation error: " + err.message);
    } finally {
      setIsPlanning(false);
    }
  };

  // Autonomous task step decomposition
  const handleDecomposeTask = async (task: Task) => {
    setIsDecomposingId(task.id);
    showToast(`Gemini is decomposing "${task.title}" into baby milestones...`);
    try {
      const res = await fetch("/api/gemini/decompose", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: task.title, description: task.description }),
      });

      if (!res.ok) throw new Error("Error fetching steps.");
      const { steps } = await res.json();

      if (Array.isArray(steps) && steps.length > 0) {
        setTasks(prev =>
          prev.map(t => {
            if (t.id === task.id) {
              const formattedSteps = steps.map((s, idx) => ({
                id: `sub-${task.id}-${idx}`,
                title: s,
                completed: false
              }));
              return { ...t, substeps: formattedSteps };
            }
            return t;
          })
        );
        showToast("✨ Autonomous substeps unlocked! Check them off sequentially.");
      }
    } catch (err: any) {
      showToast("⚠️ Milestone breakdown error: " + err.message);
    } finally {
      setIsDecomposingId(null);
    }
  };

  // Toggle a customized substep completion
  const handleToggleSubstep = (taskId: string, substepId: string) => {
    setTasks(prev =>
      prev.map(t => {
        if (t.id === taskId) {
          const updatedSubsteps = t.substeps?.map(sub => {
            if (sub.id === substepId) {
              return { ...sub, completed: !sub.completed };
            }
            return sub;
          });
          return { ...t, substeps: updatedSubsteps };
        }
        return t;
      })
    );
  };

  // Generate Interactive Productivity Score Analytics
  const handleGenerateReport = async () => {
    setIsGeneratingReport(true);
    showToast("Analyzing logged streaks and completion ratios key metrics...");
    try {
      const res = await fetch("/api/gemini/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tasks, habits }),
      });

      if (!res.ok) throw new Error("API failed to yield analytics.");
      const data = await res.json();
      setReport(data);
      showToast("✨ AI report processed! High-definition metrics live.");
    } catch (err: any) {
      showToast("⚠️ Analytics engine failure: " + err.message);
    } finally {
      setIsGeneratingReport(false);
    }
  };

  // Habit CRUD triggers
  const handleAddHabit = (name: string, frequency: "daily" | "weekly") => {
    const newHabit: Habit = {
      id: "habit-" + Date.now(),
      name,
      frequency,
      streak: 0,
      history: { "2026-06-23": false },
      createdAt: new Date().toISOString()
    };
    setHabits(prev => [newHabit, ...prev]);
    showToast("Established automatic routine trigger.");
  };

  const handleToggleHabitDate = (habitId: string, dateStr: string) => {
    setHabits(prev =>
      prev.map(h => {
        if (h.id === habitId) {
          const nextHistory = { ...h.history, [dateStr]: !h.history[dateStr] };
          
          // Re-calculate streak counts dynamically
          let streak = 0;
          const baseDate = new Date("2026-06-23T12:00:00");
          // Check consecutive preceding checked days
          for (let i = 0; i < 30; i++) {
            const tempDate = new Date(baseDate);
            tempDate.setDate(baseDate.getDate() - i);
            const key = `${tempDate.getFullYear()}-${String(tempDate.getMonth() + 1).padStart(2, "0")}-${String(tempDate.getDate()).padStart(2, "0")}`;
            if (nextHistory[key]) {
              streak++;
            } else {
              break;
            }
          }

          return {
            ...h,
            history: nextHistory,
            streak
          };
        }
        return h;
      })
    );
  };

  const handleDeleteHabit = (habitId: string) => {
    setHabits(prev => prev.filter(h => h.id !== habitId));
    showToast("Habit deleted.");
  };

  // Calculated Metrics
  const pendingCount = tasks.filter(t => t.status === "pending").length;
  const completedCount = tasks.filter(t => t.status === "completed").length;
  const highRiskCount = tasks.filter(t => t.status === "pending" && (t.urgency === "high" || t.aiPriority === "high")).length;
  
  // Client-Side fallback productivity score algorithm
  const calculateDefaultScore = () => {
    const total = tasks.length;
    if (total === 0) return 70;
    const completedRatio = completedCount / total;
    const completedWeight = Math.round(completedRatio * 60); // Max 60 pts
    
    // Streak weight
    const totalStreaks = habits.reduce((acc, h) => acc + h.streak, 0);
    const streakWeight = Math.min(totalStreaks * 4, 40); // Max 40 pts

    return Math.min(completedWeight + streakWeight + 30, 100);
  };

  const runtimeScore = report ? report.score : calculateDefaultScore();
  const remindersList = getContextReminders();

  return (
    <div className="flex flex-col md:flex-row h-screen w-screen bg-[#020617] text-slate-200 overflow-hidden font-sans">
      
      {/* SIDEBAR NAVIGATION */}
      <aside className="w-full md:w-64 bg-[#0b1120] border-r border-slate-800 flex flex-col shrink-0" id="pilot-navbar-menu">
        <div className="p-6 flex items-center justify-between border-b border-slate-850">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-indigo-600 rounded-xl flex items-center justify-center font-black text-white text-base shadow-lg shadow-indigo-900/40">
              TP
            </div>
            <div>
              <h1 className="text-md font-bold tracking-tight text-white flex items-center gap-1.5">
                TaskPilot <span className="text-indigo-400">AI</span>
              </h1>
              <p className="text-[10px] text-slate-500 font-mono">AUTONOMOUS ORBIT v1.2</p>
            </div>
          </div>
          <span className="animate-pulse w-2.5 h-2.5 rounded-full bg-emerald-500" title="AI Pilot Active"></span>
        </div>

        {/* Sidebar Nav buttons */}
        <nav className="flex-1 px-4 py-6 space-y-1.5">
          <button
            onClick={() => setActiveTab("dashboard")}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl transition-all text-sm font-medium ${
              activeTab === "dashboard"
                ? "bg-slate-800 text-white shadow-sm border-l-4 border-indigo-500"
                : "text-slate-400 hover:bg-slate-900 hover:text-white"
            }`}
          >
            <Grid className="w-4.5 h-4.5 opacity-80" />
            <span>Dashboard Hub</span>
          </button>

          <button
            onClick={() => setActiveTab("schedule")}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl transition-all text-sm font-medium ${
              activeTab === "schedule"
                ? "bg-slate-800 text-white shadow-sm border-l-4 border-indigo-500"
                : "text-slate-400 hover:bg-slate-900 hover:text-white"
            }`}
          >
            <Calendar className="w-4.5 h-4.5 opacity-80" />
            <span>Schedule Portal</span>
          </button>

          <button
            onClick={() => setActiveTab("ai-insights")}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl transition-all text-sm font-medium ${
              activeTab === "ai-insights"
                ? "bg-slate-800 text-white shadow-sm border-l-4 border-indigo-500"
                : "text-slate-400 hover:bg-slate-900 hover:text-white"
            }`}
            id="ai-insights-trigger"
          >
            <Bot className="w-4.5 h-4.5 opacity-80 text-indigo-400" />
            <span className="flex items-center gap-1.5 justify-between w-full">
              <span>Interactive Insights</span>
              <span className="bg-indigo-950 text-indigo-400 text-[9px] px-1.5 rounded font-mono border border-indigo-800/40">AI</span>
            </span>
          </button>

          <button
            onClick={() => setActiveTab("rescue")}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl transition-all text-sm font-medium ${
              activeTab === "rescue"
                ? "bg-red-950/40 text-red-200 border-l-4 border-red-500 font-bold"
                : "text-slate-400 hover:bg-slate-900 hover:text-white"
            }`}
            id="rescue-trigger"
          >
            <Zap className={`w-4.5 h-4.5 ${activeTab === "rescue" ? "text-red-400" : "text-slate-400"}`} />
            <span className="flex items-center gap-1.5 justify-between w-full">
              <span>11th-Hour Rescue</span>
              <span className="bg-red-950 text-red-400 text-[9px] px-1.5 rounded font-mono border border-red-900/40">SOS</span>
            </span>
          </button>
        </nav>

        {/* Habit Streak Widget */}
        <div className="p-4 border-t border-slate-850">
          <div className="bg-slate-900/60 border border-slate-800/80 p-3.5 rounded-xl">
            <span className="text-[10px] uppercase tracking-wider text-slate-500 font-bold block mb-1">
              🚀 Pilot Launch Streak
            </span>
            <div className="flex justify-between items-center">
              <div className="flex items-center gap-1">
                <Flame className="w-4 h-4 text-emerald-400 fill-emerald-400/20" />
                <span className="text-xs text-slate-300 font-medium">Daily consistency</span>
              </div>
              <span className="text-sm font-bold text-slate-100 font-mono">100%</span>
            </div>
            <div className="mt-2.5 h-1 bg-slate-950 rounded-full overflow-hidden">
              <div className="h-full bg-emerald-500" style={{ width: "100%" }}></div>
            </div>
          </div>
        </div>
      </aside>

      {/* MAIN LAYOUT CANVAS */}
      <main className="flex-1 flex flex-col overflow-y-auto bg-[#020617] relative">
        
        {/* Dynamic global warning banner */}
        {uiFeedback && (
          <div className="bg-indigo-600 text-white font-mono text-center text-xs py-2 px-4 shadow-lg animate-bounce sticky top-0 z-50 flex items-center justify-center gap-2">
            <Sparkles className="w-4 h-4 shrink-0" />
            <span>{uiFeedback}</span>
          </div>
        )}

        {/* Header / Brand Panel */}
        <header className="p-6 border-b border-slate-850 flex flex-col md:flex-row md:items-center justify-between gap-4 shrink-0 bg-[#070d19]/40">
          <div>
            <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
              📊 Core Center Command
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Refined performance indicators, structured study routines, and Gemini schedule compilation.
            </p>
          </div>
          
          {/* Quick AI Action widgets */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleRefinePriorities}
              disabled={isPrioritizing}
              className="bg-slate-900 border border-slate-800 hover:border-slate-700 hover:text-white px-4 py-2 rounded-xl text-xs font-mono text-slate-300 flex items-center gap-2 transition-all"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isPrioritizing ? "animate-spin" : ""}`} />
              {isPrioritizing ? "Recalculating..." : "Prioritize via Gemini"}
            </button>

            <span className="text-xs text-slate-500 font-mono hidden lg:inline">
              ⚡ Local Time: 2026-06-23
            </span>
          </div>
        </header>

        {/* Dynamic Context-Aware Reminders Bar */}
        <section className="mx-6 mt-4 p-3 bg-indigo-950/20 border border-indigo-900/30 rounded-xl flex items-center gap-3">
          <Brain className="w-5 h-5 text-indigo-400 shrink-0" />
          <div className="flex-1 min-w-0">
            <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest block mb-0.5">
              CONTEXT-AWARE RADAR REMINDER
            </span>
            <div className="text-xs text-slate-300 truncate font-mono">
              {remindersList[0]}
            </div>
          </div>
          {remindersList.length > 1 && (
            <span className="text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-indigo-900/50 text-indigo-300 border border-indigo-850 shrink-0 hidden md:inline">
              +{remindersList.length - 1} Alert(s) Pending
            </span>
          )}
        </section>

        {/* TAB 1: DASHBOARD HUB */}
        {activeTab === "dashboard" && (
          <div className="p-6 space-y-6">
            
            {/* KPI Metrics row */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4" id="density-metrics">
              <div className="bg-[#0f172a] p-4 rounded-2xl border border-slate-800/80 shadow-md flex items-center justify-between">
                <div>
                  <div className="text-slate-400 text-xs font-semibold mb-1">PRODUCTIVITY RATING</div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-emerald-400 font-mono">{runtimeScore}</span>
                    <span className="text-[10px] text-emerald-500 font-mono font-bold">Dynamic Scale</span>
                  </div>
                </div>
                <Award className="w-8 h-8 text-emerald-500/20" />
              </div>

              <div className="bg-[#0f172a] p-4 rounded-2xl border border-slate-800/80 shadow-md flex items-center justify-between">
                <div>
                  <div className="text-slate-400 text-xs font-semibold mb-1">HIGH RISK TASKS</div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-rose-500 font-mono">{highRiskCount}</span>
                    <span className="text-[10px] text-rose-400 font-mono">Need Immediate Focus</span>
                  </div>
                </div>
                <AlertCircle className="w-8 h-8 text-rose-500/20" />
              </div>

              <div className="bg-[#0f172a] p-4 rounded-2xl border border-slate-800/80 shadow-md flex items-center justify-between">
                <div>
                  <div className="text-slate-400 text-xs font-semibold mb-1">ACTIVE ASSIGNMENTS</div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-3xl font-black text-indigo-400 font-mono">{pendingCount}</span>
                    <span className="text-[10px] text-slate-500 font-mono font-bold">Remaining</span>
                  </div>
                </div>
                <ListTodo className="w-8 h-8 text-indigo-500/20" />
              </div>

              {/* Dynamic Daily Plan Starter CTA */}
              <button
                onClick={handleGenerateDailyPlan}
                disabled={isPlanning}
                className="bg-indigo-600 hover:bg-indigo-500 text-left p-4 rounded-2xl shadow-lg relative overflow-hidden group transition-all"
                id="generate-daily-plan-cta"
              >
                <div className="absolute -right-4 -top-4 w-20 h-20 bg-white/5 rounded-full blur-xl group-hover:bg-white/10 transition-all"></div>
                <div className="text-indigo-100 text-[10px] font-bold uppercase tracking-wider mb-1 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5" />
                  ASK GEMINI FOR SCHEDULING
                </div>
                <div className="text-white font-bold text-sm tracking-tight flex items-center gap-1">
                  {isPlanning ? (
                    <>
                      <LoaderIcon />
                      <span>Compiling plan...</span>
                    </>
                  ) : (
                    <>
                      <span>Generate Daily Plan</span>
                      <Play className="w-3.5 h-3.5 fill-white" />
                    </>
                  )}
                </div>
              </button>
            </div>

            {/* Split layout: Today's Focus Planner VS AI Habit Tracker / Input */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
              
              {/* Left Side: Today's Focus Action Terminal & Tasks Matrix */}
              <div className="lg:col-span-8 space-y-6">
                
                {/* AI Timetabled plan widget */}
                {dailyPlan && (
                  <div className="bg-[#0b1329]/80 border border-indigo-950 rounded-2xl p-5 shadow-2x backdrop-blur" id="ai-timetabled-plan">
                    <div className="flex items-center justify-between mb-3.5 pb-2.5 border-b border-indigo-950">
                      <div>
                        <h4 className="font-bold text-slate-100 flex items-center gap-2 text-sm uppercase font-mono tracking-widest text-indigo-300">
                          <Bot className="w-4 h-4 text-indigo-400" />
                          Today's AI Custom Timeline
                        </h4>
                        <p className="text-[10px] text-indigo-400/70 italic mt-0.5">"{dailyPlan.motivation}"</p>
                      </div>
                      <button
                        onClick={handleGenerateDailyPlan}
                        className="text-slate-400 hover:text-white"
                        title="Re-run Daily Plan Creator"
                      >
                        <RefreshCw className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                      {dailyPlan.plan.map((item, idx) => (
                        <div
                          key={`plan-item-${idx}`}
                          className="flex items-start gap-3 p-2.5 rounded-lg bg-indigo-950/20 border border-indigo-900/20 hover:border-indigo-800/40 transition-all text-xs"
                        >
                          <div className="font-mono text-indigo-300 bg-indigo-950 px-2 py-1 rounded shrink-0 border border-indigo-900">
                            {item.time}
                          </div>
                          <div className="min-w-0 flex-1">
                            <span className="font-semibold block text-slate-200">
                              {item.title}
                            </span>
                            <span className="text-[10px] text-slate-400 font-mono block">
                              📌 {item.details}
                            </span>
                          </div>
                          <span
                            className={`text-[8px] font-mono px-1.5 py-0.5 rounded uppercase font-bold shrink-0 ${
                              item.type === "task"
                                ? "bg-indigo-950 text-indigo-400 border border-indigo-800"
                                : item.type === "habit"
                                ? "bg-amber-950 text-amber-500 border border-amber-900"
                                : "bg-slate-900 text-slate-400"
                            }`}
                          >
                            {item.type}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Main Task board matrix */}
                <div className="bg-[#0f172a] rounded-2xl border border-slate-800 flex flex-col overflow-hidden" id="tasks-system-board">
                  <div className="p-4 border-b border-slate-850 flex items-center justify-between bg-slate-900/40">
                    <h3 className="font-bold text-sm tracking-wide flex items-center gap-2">
                      <ListTodo className="w-4.5 h-4.5 text-indigo-400" />
                      Active Task Board Matrix
                    </h3>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={handleRefinePriorities}
                        className="text-[11px] text-indigo-400 font-semibold hover:underline"
                        title="Run AI Priority model on empty fields"
                      >
                        Refine Priorities
                      </button>
                    </div>
                  </div>

                  {tasks.length === 0 ? (
                    <div className="p-12 text-center">
                      <Bot className="w-12 h-12 text-slate-700 mx-auto mb-3" />
                      <p className="text-sm font-semibold text-slate-400">No tasks logged in your terminal.</p>
                      <p className="text-xs text-slate-500 max-w-sm mx-auto mt-1">
                        Use the form on the right or voice commands to spawn items and trigger autonomous AI scheduling.
                      </p>
                    </div>
                  ) : (
                    <div className="divide-y divide-slate-850 max-h-[700px] overflow-y-auto">
                      {tasks.map((task) => {
                        const isHighUrgency = task.urgency === "high" || task.aiPriority === "high";
                        return (
                          <div
                            key={task.id}
                            className={`p-4 transition-all hover:bg-slate-900/40 flex flex-col gap-3 ${
                              task.status === "completed" ? "opacity-60 bg-slate-950/20" : ""
                            }`}
                          >
                            {/* Metadata and title line */}
                            <div className="flex items-start justify-between gap-2.5">
                              <div className="flex items-start gap-2.5 min-w-0">
                                <button
                                  onClick={() => handleToggleTaskStatus(task.id)}
                                  className={`mt-0.5 w-5 h-5 rounded-md border flex items-center justify-center shrink-0 transition-all ${
                                    task.status === "completed"
                                      ? "bg-emerald-600 border-emerald-500 text-white"
                                      : "border-slate-700 hover:border-slate-500 bg-slate-950"
                                  }`}
                                  title={task.status === "completed" ? "Mark incomplete" : "Mark fully completed"}
                                >
                                  {task.status === "completed" && (
                                    <span className="w-1.5 h-1.5 bg-white rounded-full"></span>
                                  )}
                                </button>

                                <div className="min-w-0">
                                  <span
                                    className={`text-sm font-bold block ${
                                      task.status === "completed" ? "line-through text-slate-500" : "text-slate-100"
                                    }`}
                                  >
                                    {task.title}
                                  </span>
                                  {task.description && (
                                    <p className="text-xs text-slate-400 mt-1 leading-relaxed line-clamp-3">
                                      {task.description}
                                    </p>
                                  )}
                                </div>
                              </div>

                              {/* Action items */}
                              <div className="flex items-center gap-1.5 shrink-0">
                                <button
                                  onClick={() => handleDeleteTask(task.id)}
                                  className="p-1 px-1.5 text-slate-650 hover:text-red-400 hover:bg-red-500/10 rounded transition-all"
                                  title="Obliterate Task"
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              </div>
                            </div>

                            {/* Badges / Dynamic indicators */}
                            <div className="flex flex-wrap items-center gap-2 text-[10px] font-mono mt-1 border-t border-slate-900/50 pt-2 pb-1">
                              <span className="text-slate-500 bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                                {task.category}
                              </span>
                              
                              <span className="text-slate-500 bg-slate-900 px-2 py-0.5 rounded border border-slate-800 flex items-center gap-1">
                                <Clock className="w-3 h-3 text-indigo-400" />
                                {task.estimateDuration}m
                              </span>

                              <span className="text-slate-500 bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                                Due: {task.dueDate === "2026-06-23" ? "Today" : task.dueDate}
                              </span>

                              {/* Urgency indicators */}
                              <span
                                className={`px-2 py-0.5 rounded uppercase font-bold text-[9px] ${
                                  task.urgency === "high"
                                    ? "bg-red-950 text-red-400 border border-red-900/40"
                                    : task.urgency === "medium"
                                    ? "bg-amber-950 text-amber-500 border border-amber-900/40"
                                    : "bg-slate-900 text-slate-500"
                                }`}
                              >
                                {task.urgency} urgency
                              </span>

                              {/* AI Explanation tag */}
                              {task.status !== "completed" && (
                                <button
                                  onClick={() => handleDecomposeTask(task)}
                                  disabled={isDecomposingId === task.id || (task.substeps && task.substeps.length > 0)}
                                  className={`px-2.5 py-0.5 rounded flex items-center gap-1 transition-all ${
                                    task.substeps && task.substeps.length > 0
                                      ? "bg-slate-800 text-slate-400 cursor-not-allowed"
                                      : "bg-indigo-950 hover:bg-indigo-900 text-indigo-400 border border-indigo-900/30 font-bold cursor-pointer"
                                  }`}
                                  title="Decompose task into bite-sized sub-steps using Gemini AI"
                                >
                                  <Sparkles className="w-3 h-3 fill-indigo-400/20" />
                                  {isDecomposingId === task.id ? "Analyzing..." : task.substeps && task.substeps.length > 0 ? "Decomposed" : "Decompose Milestone"}
                                </button>
                              )}
                            </div>

                            {/* Substep Checkboxes list */}
                            {task.substeps && task.substeps.length > 0 && (
                              <div className="bg-slate-950/60 p-3 pt-2 px-3.5 rounded-xl border border-slate-850 mt-1">
                                <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wide block mb-2">
                                  🧩 Milestones Broken Down (Gemini Autonomous Flow):
                                </span>
                                <div className="space-y-1.5">
                                  {task.substeps.map((sub) => (
                                    <label
                                      key={sub.id}
                                      className="flex items-center gap-2 cursor-pointer group text-xs text-slate-300 hover:text-white"
                                    >
                                      <input
                                        type="checkbox"
                                        checked={sub.completed}
                                        onChange={() => handleToggleSubstep(task.id, sub.id)}
                                        className="rounded bg-slate-900 border-slate-750 text-indigo-600 focus:ring-1 focus:ring-indigo-500 w-3.5 h-3.5"
                                      />
                                      <span className={sub.completed ? "line-through text-slate-550 italic" : "group-hover:translate-x-0.5 transition-transform"}>
                                        {sub.title}
                                      </span>
                                    </label>
                                  ))}
                                </div>
                              </div>
                            )}

                            {/* Real Reasoning display */}
                            {task.aiExplanation && (
                              <div className="bg-slate-950/40 border border-indigo-950 p-2.5 rounded-lg text-xs flex items-start gap-1.5 text-indigo-300 font-mono italic">
                                <Bot className="w-3.5 h-3.5 text-indigo-400 shrink-0 mt-0.5" />
                                <span>{task.aiExplanation}</span>
                              </div>
                            )}

                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              </div>

              {/* Right Side: Task Entry box and Habits */}
              <div className="lg:col-span-4 space-y-6">
                
                {/* Form Component */}
                <TaskForm onAddTask={handleAddTask} />

                {/* Habit Tracker Component */}
                <HabitTracker
                  habits={habits}
                  onAddHabit={handleAddHabit}
                  onToggleHabitDate={handleToggleHabitDate}
                  onDeleteHabit={handleDeleteHabit}
                />

                {/* Local advice panel (anti-ai-slop, clean visual) */}
                <div className="bg-slate-900 border border-slate-800 p-5 rounded-2xl relative overflow-hidden">
                  <div className="flex items-center gap-1.5 text-xs text-indigo-400 font-bold mb-2 uppercase tracking-tight">
                    <Brain className="w-4 h-4 text-indigo-400" />
                    AI STUDY RECOMMENDATION
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed font-mono">
                    Deep focus blocks require robust breaks. Check off habit milestones immediately, and export task sheets to external platforms using standard iCal formats in the Schedule tab.
                  </p>
                </div>

              </div>

            </div>

          </div>
        )}

        {/* TAB 2: SCHEDULE PORTAL */}
        {activeTab === "schedule" && (
          <div className="p-6">
            <CalendarExport tasks={tasks} />
          </div>
        )}

        {/* TAB 3: INSIGHTS & REPORTS */}
        {activeTab === "ai-insights" && (
          <div className="p-6 space-y-6" id="insights-studio">
            
            <div className="bg-[#0b1120] border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
              <div className="absolute top-0 right-0 w-48 h-48 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none"></div>

              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5 mb-5">
                <div>
                  <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-indigo-400" />
                    Autonomous Performance coaching cockpit
                  </h3>
                  <p className="text-xs text-slate-400 mt-1">
                    Calculate precise metrics, study optimizations, and unlock actionable study advice compiled dynamically.
                  </p>
                </div>

                <button
                  onClick={handleGenerateReport}
                  disabled={isGeneratingReport}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-xs py-2.5 px-4 rounded-xl transition-all shadow-md flex items-center gap-2 justify-center shrink-0"
                >
                  {isGeneratingReport ? (
                    <>
                      <LoaderIcon />
                      <span>Decompressing insights...</span>
                    </>
                  ) : (
                    <>
                      <RefreshCw className="w-4 h-4" />
                      <span>Compile AI Analytical Report</span>
                    </>
                  )}
                </button>
              </div>

              {!report ? (
                <div className="text-center py-16 px-4 bg-slate-950/40 rounded-xl border border-dashed border-slate-800">
                  <Bot className="w-12 h-12 text-indigo-400/40 mx-auto mb-3" />
                  <h4 className="font-bold text-slate-300 text-sm">Productivity score not analyzed in this micro-session</h4>
                  <p className="text-xs text-slate-500 max-w-sm mx-auto mt-1">
                    Ensure routine tasks are added, or click "Compile AI Analytical Report" to fetch Gemini recommendations instantly!
                  </p>
                </div>
              ) : (
                <div className="space-y-6">
                  
                  {/* Rating / Score Callouts */}
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    
                    <div className="bg-slate-950 p-4 rounded-xl border border-indigo-950">
                      <span className="text-[10px] uppercase font-mono text-slate-500 tracking-wider">PRODUCTIVITY VALUATION</span>
                      <div className="flex items-baseline gap-2 mt-1">
                        <span className="text-4xl font-black text-emerald-400 font-mono">{report.score}</span>
                        <span className="text-xs text-slate-500">out of 100</span>
                      </div>
                      <p className="text-[10px] text-emerald-500 mt-2 font-mono">⚡ Refined base value</p>
                    </div>

                    <div className="bg-slate-950 p-4 rounded-xl border border-slate-850 md:col-span-2">
                      <span className="text-[10px] uppercase font-mono text-slate-500 tracking-wider">PERFORMANCE EXECUTIVE BRIEFING</span>
                      <p className="text-xs text-slate-200 mt-2 leading-relaxed">
                        {report.insightSummary}
                      </p>
                    </div>

                  </div>

                  {/* High Risk Breakdown */}
                  <div className="bg-red-950/15 border border-red-950 p-4 rounded-xl">
                    <span className="text-[10px] uppercase font-bold text-red-400 tracking-wider flex items-center gap-1">
                      <AlertCircle className="w-4 h-4" />
                      COACH RADAR: HIGH-RISK CONSTRAINTS REPORT
                    </span>
                    <p className="text-xs text-slate-300 mt-1 leading-relaxed">
                      {report.highRiskInsights || "No urgent high-threat deadlines detected."}
                    </p>
                  </div>

                  {/* Recommendations */}
                  <div>
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-3">
                      💡 CORE STRATEGY RECOMMENDATIONS
                    </span>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {report.recommendations.map((rec, idx) => (
                        <div key={idx} className="bg-slate-950 p-4 rounded-xl border border-slate-850 flex items-start gap-2.5">
                          <CheckCircle className="w-4.5 h-4.5 text-indigo-400 shrink-0 mt-0.5" />
                          <p className="text-xs text-slate-300 leading-relaxed">
                            {rec}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Habit streaks feedback */}
                  <div className="bg-amber-950/15 border border-amber-950 p-4 rounded-xl flex items-start gap-3">
                    <Flame className="w-5 h-5 text-amber-500 fill-amber-500/10 shrink-0 mt-0.5" />
                    <div>
                      <span className="text-[10px] uppercase font-bold text-amber-400 tracking-wider">
                        HABIT METRICS FEEDBACK
                      </span>
                      <p className="text-xs text-slate-300 mt-1 leading-relaxed">
                        {report.habitStreaksFeedback || "Establish active streaks to unlock routine metrics analytics."}
                      </p>
                    </div>
                  </div>

                  {/* Achievements Badge list */}
                  <div>
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-3">
                      🏆 UNLOCKED REVENUE / REPUTATION MILESTONES
                    </span>
                    <div className="flex flex-wrap gap-2">
                      {report.achievements.map((ach, idx) => (
                        <span key={idx} className="bg-emerald-950/40 text-emerald-400 border border-emerald-900/40 rounded-full px-3.5 py-1 text-xs font-semibold uppercase tracking-tight flex items-center gap-1.5">
                          <Award className="w-3.5 h-3.5 text-emerald-400" />
                          {ach}
                        </span>
                      ))}
                    </div>
                  </div>

                </div>
              )}
            </div>

            {/* General FAQs on utilizing AI metrics */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-slate-900/40 p-4 rounded-xl border border-slate-800">
                <span className="text-xs font-bold text-indigo-400 font-mono block mb-2">
                  Q: How is prioritization defined?
                </span>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Our customized Gemini micro-model parses task titles and deadlines, allocating dynamic high-priority indices to minimize stress.
                </p>
              </div>

              <div className="bg-slate-900/40 p-4 rounded-xl border border-slate-800">
                <span className="text-xs font-bold text-indigo-400 font-mono block mb-2">
                  Q: Why are streaks essential?
                </span>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Habit tracking evaluates consistent routine triggers. Continuous checks fuel the productivity scoreboard significantly.
                </p>
              </div>

              <div className="bg-slate-900/40 p-4 rounded-xl border border-slate-800">
                <span className="text-xs font-bold text-indigo-400 font-mono block mb-2">
                  Q: What are high risk alerts?
                </span>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Tasks approaching active deadlines classified past the warning window trigger prominent visual reminders on your dashboard.
                </p>
              </div>
            </div>

          </div>
        )}

        {/* TAB 4: 11TH-HOUR RESCUE */}
        {activeTab === "rescue" && (
          <div className="p-6">
            <RescueCenter tasks={tasks} onToggleTaskStatus={handleToggleTaskStatus} />
          </div>
        )}

      </main>
    </div>
  );
}

// Micro loader SVG
function LoaderIcon() {
  return (
    <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
  );
}
